import java.util.Scanner;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    
    static class Member {
        protected String name;
        protected String email;
        protected String password;
        

        @Override
        public String toString() {
            return "Member [name=" + name + ", email=" + email + ", password=" + password + "]";
        }
        
        public String getName() {
            return name;
        }
        public void setName(String name) {
            this.name = name;
        }
        public String getEmail() {
            return email;
        }
        public void setEmail(String email) {
            this.email = email;
        }
        public String getPassword() {
            return password;
        }
        public void setPassword(String password) {
            this.password = password;
        }
        
        
    }
    
    static class Student extends Member {
        String school;
        boolean working;
        String tel;
        
        public String getSchool() {
            return school;
        }
        public void setSchool(String school) {
            this.school = school;
        }
        public boolean isWorking() {
            return working;
        }
        public void setWorking(boolean working) {
            this.working = working;
        }
        public String getTel() {
            return tel;
        }
        public void setTel(String tel) {
            this.tel = tel;
        }
    }
    
        static Member[] members = new Member[100];
        
        static int index = 0;
        
        //1)키보드 입력을 처리할 객체 준비
        static Scanner keyIn = new Scanner(System.in); 
    
    public static void main(String[] args) {
        
        while (true ) {
            String menu = promptMenu();
            if (menu.equals("1")) {
                serviceStudentMenu();
            }else {
                System.out.println("사요나라");
                break;
            }
        }
        
        keyIn.close();

        

    }

    private static void serviceStudentMenu() {
        while (true) {
                System.out.println("학생 관리>");
                String command = keyIn.nextLine();
                if (command.equals("list")) {
                    printMembers();
                }else if (command.equals("add")) {
                    inputMembers();
                }else if (command.equals("quit")) {
                    break;
                }else {
                    System.out.println("유효하지 않은 명령입니다");
                }                
        }
    }

    private static String promptMenu() {
        System.out.println("[메뉴]");
        System.out.println("1. 학생 관리");
        System.out.println("2. 강사 관리");
        System.out.println("3. 매니저 관리");
        System.out.println("0. 종료");
        
        while (true) {
            System.out.print("메뉴 번호> ");
            
            String menu = keyIn.nextLine();
            System.out.println(menu);
            
            switch (menu) {
            case "1":
            case "2":
            case "3":
            case "0":
                return menu;
            default:
                System.out.println("메뉴 번호가 유효하지 않습니다");
            }            
        }
        
//        if (menu.equals("1")) {
//            inputMembers();
//            
//            printMembers();            
//        }else {
//            System.out.println("메뉴 번호가 유효하지 않습니다");
//        }
    }
    
    static void printMembers() {
        for (int i = 0; i < index; i++)
        System.out.printf("%s, %s, %s\n",members[i].getName(),members[i].getEmail(),members[i].getPassword());

    }
    
    static void inputMembers() {
        //2) 사용자로부터 회원 정보 입력받기
        while (true) {
            //members[index] = new Member();
            Member m = new Member();
            
            System.out.println("이름?");
            m.setName(keyIn.nextLine());
            
            System.out.println("이메일?");
            m.setEmail(keyIn.nextLine());
            
            System.out.println("암호?");
            m.setPassword(keyIn.nextLine());
            
            members[index++] = m;
            
            //index++;
            
            System.out.println("계속하시겠습니까? (y/n)");
            String answer = keyIn.nextLine();
            if(answer.toLowerCase().equals("n"))
                break;
        }
    }
}
