import java.util.Scanner;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    
    static class Member {
        protected String name;
        protected String email;
        protected String password;
        

        @Override
        public String toString() {
            return "Member [name=" + name + ", email=" + email + ", password=" + password + "]";
        }
        
        public String getName() {
            return name;
        }
        public void setName(String name) {
            this.name = name;
        }
        public String getEmail() {
            return email;
        }
        public void setEmail(String email) {
            this.email = email;
        }
        public String getPassword() {
            return password;
        }
        public void setPassword(String password) {
            this.password = password;
        }
        
        
    }
    
        static Member[] members = new Member[100];
        
        static int index = 0;
        
        //1)키보드 입력을 처리할 객체 준비
        static Scanner keyIn = new Scanner(System.in); 
    
    public static void main(String[] args) {

        inputMembers();
        
        printMembers();
        
        keyIn.close();

        

    }
    
    static void printMembers() {
        for (int i = 0; i < index; i++)
        System.out.printf("%s, %s, %s\n",members[i].getName(),members[i].getEmail(),members[i].getPassword());

    }
    
    static void inputMembers() {
        //2) 사용자로부터 회원 정보 입력받기
        while (true) {
            //members[index] = new Member();
            Member m = new Member();
            
            System.out.println("이름?");
            m.setName(keyIn.nextLine());
            
            System.out.println("이메일?");
            m.setEmail(keyIn.nextLine());
            
            System.out.println("암호?");
            m.setPassword(keyIn.nextLine());
            
            members[index++] = m;
            
            //index++;
            
            System.out.println("계속하시겠습니까? (y/n)");
            String answer = keyIn.nextLine();
            if(answer.toLowerCase().equals("n"))
                break;
        }
    }
}
